### ISSUE TITLE
Not loading QR Codes in Mautic 4.4.11

### ISSUE THREAD

**Issue by alexhammerschmied** [hostnetbr/mautic-googleauthenticator#5]
I added the plugin to a 4.4.11 Mautic and with the first admin user it was no problem to switch to 2FA and scan the QR Code.
But with the other users the image (QR Code) doesn't get loaded. 

Any idea why this is happening?

**Comment by mzagmajster** [comment]
Its because of the line here:

https://github.com/hostnetbr/mautic-googleauthenticator/blob/master/HostnetAuthBundle/Helper/QrHelper.php#L86

Google APIs url does not work anymore.

I have forked and migrated plugin to Mautic 5 & Mautic 4, here are the links if anyone is interested:

- https://github.com/mzagmajster/mautic-googleauthenticator/tree/dev_mautic4
- https://github.com/mzagmajster/mautic-googleauthenticator/tree/dev_mautic5

Hope it helps.
